plugin:
- steam
#- test2
# if you don't want to set proxy, please fill in null
#proxy: null
proxy:
  http: http://127.0.0.1:7890
  https: socks5://127.0.0.1:7891
autoupdateDatabase: false
gitToken: 'your token'
lang: zh
# if you cannot directly connect to the github server, please fill in other urls here
#updateRepo: 'url'
updateRepo: null
version: '0.1'