# Form implementation generated from reading ui file '/home/keiplyer/桌面/qt/ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox

class Ui_FGI_GAME_YAML_MAKER(object):
    def setupUi(self, FGI_GAME_YAML_MAKER):
        FGI_GAME_YAML_MAKER.setObjectName("FGI_GAME_YAML_MAKER")
        FGI_GAME_YAML_MAKER.resize(800, 600)
        FGI_GAME_YAML_MAKER.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Chinese, QtCore.QLocale.Country.China))
        self.widget = QtWidgets.QWidget(FGI_GAME_YAML_MAKER)
        self.widget.setObjectName("widget")
        FGI_GAME_YAML_MAKER.setCentralWidget(self.widget)
        self.menubar = QtWidgets.QMenuBar(FGI_GAME_YAML_MAKER)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.global_proxy = QtWidgets.QMenu(self.menu)
        self.global_proxy.setEnabled(True)
        self.global_proxy.setTearOffEnabled(False)
        self.global_proxy.setObjectName("global_proxy")
        self.about = QtWidgets.QMenu(self.menubar)
        self.about.setObjectName("about")
        FGI_GAME_YAML_MAKER.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FGI_GAME_YAML_MAKER)
        self.statusbar.setObjectName("statusbar")
        FGI_GAME_YAML_MAKER.setStatusBar(self.statusbar)
        self.check_update = QtGui.QAction(FGI_GAME_YAML_MAKER)
        self.check_update.setObjectName("check_update")
        self.update_dayabase = QtGui.QAction(FGI_GAME_YAML_MAKER)
        self.update_dayabase.setObjectName("update_dayabase")
        self.status = QtGui.QAction(FGI_GAME_YAML_MAKER)
        self.status.setCheckable(True)
        self.status.setChecked(True)
        self.status.setObjectName("status")
        self.set_proxy = QtGui.QAction(FGI_GAME_YAML_MAKER)
        self.set_proxy.setObjectName("set_proxy")
        self.open_source = QtGui.QAction(FGI_GAME_YAML_MAKER)
        self.open_source.setObjectName("open_source")
        self.global_proxy.addAction(self.status)
        self.global_proxy.addAction(self.set_proxy)
        self.menu.addAction(self.check_update)
        self.menu.addAction(self.update_dayabase)
        self.menu.addAction(self.global_proxy.menuAction())
        self.about.addAction(self.open_source)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.about.menuAction())

        self.retranslateUi(FGI_GAME_YAML_MAKER)
        QtCore.QMetaObject.connectSlotsByName(FGI_GAME_YAML_MAKER)
    def retranslateUi(self, FGI_GAME_YAML_MAKER):
        _translate = QtCore.QCoreApplication.translate
        FGI_GAME_YAML_MAKER.setWindowTitle(_translate("FGI_GAME_YAML_MAKER", "FGI游戏yaml文件生成器"))
        self.menu.setTitle(_translate("FGI_GAME_YAML_MAKER", "菜单"))
        self.global_proxy.setTitle(_translate("FGI_GAME_YAML_MAKER", "全局代理"))
        self.about.setTitle(_translate("FGI_GAME_YAML_MAKER", "关于"))
        self.check_update.setText(_translate("FGI_GAME_YAML_MAKER", "检查更新"))
        self.update_dayabase.setText(_translate("FGI_GAME_YAML_MAKER", "更新上游数据库"))
        self.status.setText(_translate("FGI_GAME_YAML_MAKER", "开启"))
        self.set_proxy.setText(_translate("FGI_GAME_YAML_MAKER", " 配置"))
        self.open_source.setText(_translate("FGI_GAME_YAML_MAKER", "开源地址"))

def qtmsgbox(msgstr: str,icon=QMessageBox.Icon.Information,title:str='FGI游戏yaml文件生成器',button: QMessageBox.StandardButton=QMessageBox.StandardButton.Ok):
   msg = QMessageBox()
   msg.setIcon(icon)
   msg.setText(msgstr)
   msg.setWindowTitle(title)
   msg.setStandardButtons(button)
   return msg.exec()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FGI_GAME_YAML_MAKER = QtWidgets.QMainWindow()
    ui = Ui_FGI_GAME_YAML_MAKER()
    ui.setupUi(FGI_GAME_YAML_MAKER)
    #ui.about.triggered.connect(t)
    print(qtmsgbox(msgstr='你好')==QMessageBox.StandardButton.Ok)
    FGI_GAME_YAML_MAKER.show()
    sys.exit(app.exec())

