name: Python application

on:
  push:
    branches:
      - dev
      - master
    paths:
      - '**.py'
      - '**.yml'
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache Poetry dependencies
        id: check_cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dependencies
        if: steps.check_cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          python -m poetry install
      - name: Test with unittest
        run: |
          python -m poetry run python -m unittest tests.unit_test
