name: Test Main Program

on:
  push:
    branches:
      - fix-ci
      - dev
      - master
    paths:
      - '**.py'
      - 'Test*.yml'
      - '**.lock'
      - '**.yaml'
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
      - name: Check Cache
        id: cache-check
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/pdm.lock') }}
      - name: Install dependencies
        if: steps.cache-check.outputs.cache-hit != 'true'
        run: pdm install
      - name: Test with unittest
        run: |
          pdm run python -m unittest tests.unit_test
