name: Test Default Hooks

on:
  push:
    branches:
      - fix-ci
      - dev
      - master
    paths:
      - '**.py'
      - '**.yml'
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.11
          cache: true
      - name: Test with unittest
        run: |
          pdm run python -m unittest tests.hook_test