name: Test Main Program

on:
  push:
    branches:
      - fix-ci
      - dev
      - master
    paths:
      - '**.py'
      - '**.yml'
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.11
          cache: true
      - name: Check Cache
        id: cache-check
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pdm.lock') }}
      - name: Install dependencies
        if: steps.cache-check.outputs.cache-hit != 'true'
        run: pdm install
      - name: Test with unittest
        run: |
          pdm run python -m unittest tests.unit_test
